services:
  db:
    image: postgis/postgis:16-3.5
    container_name: geoapi_db_dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: geoapi
      POSTGRES_USER: geoapi
      POSTGRES_PASSWORD: geoapi
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U geoapi -d geoapi" ]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.dev
    image: geoapi_api_dev:latest
    container_name: geoapi_api_dev
    volumes:
      - ./:/workspace:delegated
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    stdin_open: true # Enable interactive mode for debugging
    tty: true # Allocate a pseudo-TTY for better terminal experience

  notebook:
    image: python:3.9-slim
    container_name: geoapi_notebook_dev
    working_dir: /workspace
    command: >
      bash -c "
        echo 'Installing Jupyter and mapboxgl...' &&
        pip install --no-cache-dir --upgrade pip &&
        pip install --no-cache-dir 'ipython==7.34.0' &&
        pip install --no-cache-dir 'jupyterlab==3.6.7' &&
        pip install --no-cache-dir 'requests==2.28.0' &&
        pip install --no-cache-dir 'pandas==1.5.3' &&
        pip install --no-cache-dir 'geopandas==0.12.2' &&
        pip install --no-cache-dir 'shapely==1.8.5' &&
        pip install --no-cache-dir 'numpy==1.24.0' &&
        pip install --no-cache-dir 'mapboxgl==0.10.2' &&
        echo 'Testing mapboxgl import...' &&
        python -c 'from mapboxgl.viz import ChoroplethViz; print(\"Mapboxgl working!\")' &&
        echo 'Starting Jupyter Lab...' &&
        jupyter lab --ip=0.0.0.0 --port=8888 --allow-root --ServerApp.token='' --ServerApp.password=''
      "
    volumes:
      - ./:/workspace:delegated
    ports:
      - "8888:8888"
    depends_on:
      - api

volumes:
  db_data:
