services:
  db:
    image: postgis/postgis:16-3.5
    container_name: geoapi_db_dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: geoapi
      POSTGRES_USER: geoapi
      POSTGRES_PASSWORD: geoapi
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U geoapi -d geoapi" ]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.dev
    image: geoapi_api_dev:latest
    container_name: geoapi_api_dev
    volumes:
      - ./:/workspace:delegated
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    stdin_open: true # Enable interactive mode for debugging
    tty: true # Allocate a pseudo-TTY for better terminal experience

  notebook:
    image: jupyter/scipy-notebook:latest
    container_name: geoapi_notebook_dev
    working_dir: /home/jovyan/work
    user: root
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - GRANT_SUDO=yes
    command: >
      bash -c "
        echo 'Installing required packages...' &&
        pip install --no-cache-dir requests pandas mapboxgl folium &&
        echo 'Starting Jupyter Lab...' &&
        start-notebook.sh --NotebookApp.token='' --NotebookApp.password='' --ip=0.0.0.0 --port=8888 --allow-root
      "
    volumes:
      - ./:/home/jovyan/work:delegated
    ports:
      - "8888:8888"
    depends_on:
      - api

volumes:
  db_data:
